function generateWebsite(prompt) {

const text = prompt.toLowerCase();

let title = "Your New Website";
let description = "A modern website generated by AniVora.";

if (text.includes("restaurant")) {
title = "Taste Something Amazing";
description =
"Discover delicious food, beautiful experiences and a menu made for you.";
}

else if (
text.includes("portfolio") ||
text.includes("developer")
) {
title = "Build. Create. Inspire.";
description =
"A professional portfolio showcasing projects, skills and experience.";
}

else if (text.includes("fashion")) {
title = "Define Your Style";
description =
"Discover a modern collection created for people who want to stand out.";
}

else if (text.includes("fitness")) {
title = "Become Your Strongest Self";
description =
"Training programs, expert coaching and everything you need to reach your goals.";
}

else if (text.includes("barber")) {
title = "Look Sharp. Feel Confident.";
description =
"Professional grooming and modern styles designed around you.";
}

else if (text.includes("business")) {
title = "Grow Your Business";
description =
"A professional digital presence designed to help your business grow.";
}

return {
title,
description
};
}
