export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      error: "Method not allowed"
    });
  }

  try {
    const { prompt } = req.body || {};

    // Validate prompt
    if (!prompt || typeof prompt !== "string" || !prompt.trim()) {
      return res.status(400).json({
        success: false,
        error: "Website description is required."
      });
    }

    // Get OpenAI API key
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({
        success: false,
        error: "OPENAI_API_KEY is not configured in Vercel."
      });
    }

    // Ask OpenAI to generate the website
    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",

      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`
      },

      body: JSON.stringify({
        model: "gpt-5.6-luna",

        input: [
          {
            role: "system",
            content: `
You are AniVora Builder, an AI website generator.

The user will describe a website they want.

Create a complete, modern, responsive website based on that description.

Return ONLY valid JSON.

The JSON must have exactly these fields:

{
  "name": "Website name",
  "headline": "Main headline",
  "description": "Short website description",
  "button": "Main button text",
  "color": "#hexcolor",
  "html": "Complete HTML"
}

IMPORTANT:

- The html field must contain the complete website HTML.
- Use inline CSS.
- Do not use JavaScript.
- Do not use <script> tags.
- Do not use external CSS files.
- Make the website responsive.
- Make it look professional on phones and desktops.
- Use semantic HTML.
- Include sections appropriate to the user's request.
- Do not force every website into the same layout.
- A restaurant should look like a restaurant.
- A portfolio should look like a portfolio.
- A school should look like a school.
- An online store should look like an online store.
- A SaaS website should look like a SaaS website.
- Use realistic sample content when the user does not provide exact content.
- Do not mention that the website was generated by AI.
- Do not put Markdown fences around the JSON.
- Do not put explanations before or after the JSON.

For a restaurant, consider sections such as:
- Navigation
- Hero
- Menu
- Reservations
- Opening hours
- Reviews
- Location
- Contact
- WhatsApp ordering

Only include sections that make sense for the user's request.
`
          },

          {
            role: "user",
            content: prompt.trim()
          }
        ],

        temperature: 0.7
      })
    });

    const data = await response.json();

    // OpenAI request failed
    if (!response.ok) {
      console.error("OpenAI API error:", data);

      return res.status(response.status).json({
        success: false,
        error:
          data?.error?.message ||
          "OpenAI API request failed."
      });
    }

    // Get output text
    let output = "";

    if (typeof data.output_text === "string") {
      output = data.output_text;
    }

    // Fallback: extract text from the Responses API output
    if (!output && Array.isArray(data.output)) {
      for (const item of data.output) {
        if (Array.isArray(item.content)) {
          for (const content of item.content) {
            if (
              content &&
              typeof content.text === "string"
            ) {
              output += content.text;
            }
          }
        }
      }
    }

    output = output.trim();

    console.log("AniVora OpenAI output length:", output.length);

    if (!output) {
      console.error("OpenAI returned no text:", data);

      return res.status(500).json({
        success: false,
        error: "OpenAI returned an empty response."
      });
    }

    // Remove accidental Markdown code fences
    output = output
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/\s*```$/i, "")
      .trim();

    // Parse generated JSON
    let website;

    try {
      website = JSON.parse(output);
    } catch (error) {
      console.error("AniVora JSON parse error:", output);

      return res.status(500).json({
        success: false,
        error: "AniVora AI returned invalid website data.",
        raw: output.substring(0, 1000)
      });
    }

    // Make sure the required fields exist
    if (
      !website ||
      typeof website !== "object" ||
      typeof website.html !== "string"
    ) {
      console.error("Invalid website object:", website);

      return res.status(500).json({
        success: false,
        error: "AniVora AI did not return a valid website."
      });
    }

    // Fill missing optional fields safely
    website.name =
      typeof website.name === "string"
        ? website.name
        : "AniVora Website";

    website.headline =
      typeof website.headline === "string"
        ? website.headline
        : "Welcome";

    website.description =
      typeof website.description === "string"
        ? website.description
        : "";

    website.button =
      typeof website.button === "string"
        ? website.button
        : "Get Started";

    website.color =
      typeof website.color === "string"
        ? website.color
        : "#6C63FF";

    // Return exactly what the frontend expects
    return res.status(200).json({
      success: true,
      website: website
    });

  } catch (error) {
    console.error("AniVora backend error:", error);

    return res.status(500).json({
      success: false,
      error:
        error?.message ||
        "AniVora AI generation failed."
    });
  }
}
